name: TerminatorPlus
main: net.nuggetmc.tplus.TerminatorPlus
version: 3.1-BETA
api-version: 1.16
author: HorseNuggets

permissions:
  terminatorplus.*:
    description: TerminatorPlus parent permission.
    default: op
    children:
      terminatorplus.manage: true
  terminatorplus.manage:
    description: Allows for TerminatorPlus bot management.
    default: op